detect_cancer <- function(data) {

require(tidyverse, warn.conflicts = F, quietly = T)
  
patrones <- "CA[. ]|C[AÁ]NCER|ONCOL[OÓ]GIC|QT|RT|QUIMIOTERAPIA|RADIOTERAPIA|QMT|DOCETAXEL|CICLOFOSFAMIDA|CARBOPLATINO|PACLITAXEL|TRASTUZUMAB|TRIPTORELINA|LEUPROLIDE|TAMOXIFENO|CMF|FULVESTRANT|NV|GEMCITABINE|ENZALUTAMIDA|OXALIPLATINO|AZACITIDINA|ZOLEDRONICO|PEMBROLIZUMAB|PEMETREXED|TRIFLURIDINA|CAPECITABINE|METOTREXATO|BRENTUXIMAB|GAZYVA|MELANOMA|LEUCEMIA|LLA|SMD|LMMC|LDCG|LH|LNH|HODKIN|MTS|SARCOMA|MIELOMA|PLASMOCITOMA|MESOTELIOMA|ASTROCITOMA|BLASTOMA|GLIOMA|EPENDIMOMA|PLEXOS COROIDEOS|PLEXO COROIDES|PINEOCITOMA|MEDULOEPITELIOMA|SCHWANNOMA|HEMANGIOPERICITOMA|MIELOPROLIF|MIELODISPLAS|HISTIOCITOSIS|MET[ÁA]STASIS|SECUNDARISMO|MALIGN|PROLACTINOMA|CARCINO|FEOCROMOCITOMA|SARCOMATOSIS|SEMINOMA|GERMINOMA|INVASOR|GERMINALES|POLIEMBRIOMA|HIPERNEFROMA|WILMS|HODGKIN|MICOSIS FUNGOIDE|S[ÉE]ZARY|MALTOMA|MASTOCITOMA|BL[ÁA]STICO|MACROGLOBULINEMIA|MONOCLONAL|POLICITEMIA|MIELOESCLEROSIS|MIELOFIBROSIS|MIELODISPLASIA|MIELODISPL[ÁA]SICO|INFILTRACI[ÓO]N|C[ÉE]LULAS CLARAS|TROMBOCITEMIA ESENCIAL|BOWEN|S[ÉE]RTOLI|LEYDIG|HISTIOCITOMA FIBROSO MALIGNO|HISTIOCITOSIS|SENO ENDOD[EÉ]RMICO|TUMOR RABDOIDE|ANEMIA REFRACTARIA"


data %>% 
  mutate(CANCER = case_when(
    str_detect(string = DIAGNOSTICO, pattern = patrones) ~ "SI",
    str_detect(string = DIAGNOSTICO, pattern = "LINFOMA") &
    str_detect(string = DIAGNOSTICO, pattern = "ADENOLINFOMA" , negate = T ) ~ "SI",
    str_detect(string = DIAGNOSTICO, pattern = "BL[ÁA]STICA")&
    str_detect(string = DIAGNOSTICO, pattern = "MEGALOBLASTICA" , negate = T ) ~ "SI"))

}
